#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : roboto
Version  : 2.138
Release  : 3
URL      : https://github.com/google/roboto/archive/v2.138.tar.gz
Source0  : https://github.com/google/roboto/archive/v2.138.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0
Requires: roboto-data = %{version}-%{release}
Requires: roboto-license = %{version}-%{release}
BuildRequires : fonttools
Patch1: 0001-add-build-install-makefile-targets.patch

%description
Spiro release 0.01
4 May 2007
Raph Levien
This is a very rough release of the Spiro toolset that I've been using
to create my fonts. The main program is ppedit, and there's a more

%package data
Summary: data components for the roboto package.
Group: Data

%description data
data components for the roboto package.


%package license
Summary: license components for the roboto package.
Group: Default

%description license
license components for the roboto package.


%prep
%setup -q -n roboto-2.138
cd %{_builddir}/roboto-2.138
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604085491
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1604085491
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/roboto
cp %{_builddir}/roboto-2.138/LICENSE %{buildroot}/usr/share/package-licenses/roboto/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/roboto-2.138/third_party/fontcrunch/LICENSE %{buildroot}/usr/share/package-licenses/roboto/a118861172e3884edbc819521f390e11bdb5fb9f
cp %{_builddir}/roboto-2.138/third_party/spiro/LICENSE %{buildroot}/usr/share/package-licenses/roboto/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
cp %{_builddir}/roboto-2.138/third_party/spiro/ppedit/gpl.txt %{buildroot}/usr/share/package-licenses/roboto/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/fonts/roboto/Roboto-Black.ttf
/usr/share/fonts/roboto/Roboto-BlackItalic.ttf
/usr/share/fonts/roboto/Roboto-Bold.ttf
/usr/share/fonts/roboto/Roboto-BoldItalic.ttf
/usr/share/fonts/roboto/Roboto-Italic.ttf
/usr/share/fonts/roboto/Roboto-Light.ttf
/usr/share/fonts/roboto/Roboto-LightItalic.ttf
/usr/share/fonts/roboto/Roboto-Medium.ttf
/usr/share/fonts/roboto/Roboto-MediumItalic.ttf
/usr/share/fonts/roboto/Roboto-Regular.ttf
/usr/share/fonts/roboto/Roboto-Thin.ttf
/usr/share/fonts/roboto/Roboto-ThinItalic.ttf
/usr/share/fonts/roboto/RobotoCondensed-Bold.ttf
/usr/share/fonts/roboto/RobotoCondensed-BoldItalic.ttf
/usr/share/fonts/roboto/RobotoCondensed-Italic.ttf
/usr/share/fonts/roboto/RobotoCondensed-Light.ttf
/usr/share/fonts/roboto/RobotoCondensed-LightItalic.ttf
/usr/share/fonts/roboto/RobotoCondensed-Regular.ttf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/roboto/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/roboto/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/roboto/a118861172e3884edbc819521f390e11bdb5fb9f
