#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : roboto
Version  : 2.138
Release  : 1
URL      : https://github.com/google/roboto/archive/v2.138.tar.gz
Source0  : https://github.com/google/roboto/archive/v2.138.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0
Requires: roboto-data = %{version}-%{release}
Requires: roboto-license = %{version}-%{release}
Requires: Cython
Requires: fonttools
Requires: numpy
Requires: scipy
BuildRequires : fonttools
Patch1: 0001-add-build-install-makefile-targets.patch

%description
Spiro release 0.01
4 May 2007
Raph Levien
This is a very rough release of the Spiro toolset that I've been using
to create my fonts. The main program is ppedit, and there's a more

%package data
Summary: data components for the roboto package.
Group: Data

%description data
data components for the roboto package.


%package license
Summary: license components for the roboto package.
Group: Default

%description license
license components for the roboto package.


%prep
%setup -q -n roboto-2.138
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550165345
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1550165345
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/roboto
cp LICENSE %{buildroot}/usr/share/package-licenses/roboto/LICENSE
cp third_party/fontcrunch/LICENSE %{buildroot}/usr/share/package-licenses/roboto/third_party_fontcrunch_LICENSE
cp third_party/spiro/LICENSE %{buildroot}/usr/share/package-licenses/roboto/third_party_spiro_LICENSE
cp third_party/spiro/ppedit/gpl.txt %{buildroot}/usr/share/package-licenses/roboto/third_party_spiro_ppedit_gpl.txt
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/fonts/roboto/Roboto-Black.ttf
/usr/share/fonts/roboto/Roboto-BlackItalic.ttf
/usr/share/fonts/roboto/Roboto-Bold.ttf
/usr/share/fonts/roboto/Roboto-BoldItalic.ttf
/usr/share/fonts/roboto/Roboto-Italic.ttf
/usr/share/fonts/roboto/Roboto-Light.ttf
/usr/share/fonts/roboto/Roboto-LightItalic.ttf
/usr/share/fonts/roboto/Roboto-Medium.ttf
/usr/share/fonts/roboto/Roboto-MediumItalic.ttf
/usr/share/fonts/roboto/Roboto-Regular.ttf
/usr/share/fonts/roboto/Roboto-Thin.ttf
/usr/share/fonts/roboto/Roboto-ThinItalic.ttf
/usr/share/fonts/roboto/RobotoCondensed-Bold.ttf
/usr/share/fonts/roboto/RobotoCondensed-BoldItalic.ttf
/usr/share/fonts/roboto/RobotoCondensed-Italic.ttf
/usr/share/fonts/roboto/RobotoCondensed-Light.ttf
/usr/share/fonts/roboto/RobotoCondensed-LightItalic.ttf
/usr/share/fonts/roboto/RobotoCondensed-Regular.ttf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/roboto/LICENSE
/usr/share/package-licenses/roboto/third_party_fontcrunch_LICENSE
/usr/share/package-licenses/roboto/third_party_spiro_LICENSE
/usr/share/package-licenses/roboto/third_party_spiro_ppedit_gpl.txt
